name: Tests

on:
  - push
  - pull_request

jobs:
  linux:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo pip install -r requirements.txt
      - name: Run tests
        run: python3 tests/test.py
